# Copyright (c) 2017 CloudZero - ALL RIGHTS RESERVED - PROPRIETARY AND CONFIDENTIAL
# Unauthorized copying of this file and/or project, via any medium is strictly prohibited.
# Direct all questions to legal@cloudzero.com


service: pyfaaster-example

plugins:
  - serverless-prune-plugin
  - serverless-dynamodb-autoscaling
  - serverless-pseudo-parameters

frameworkVersion: ">=1.2.0 <2.0.0"

package:
  exclude:
    - ./**
  include:
    - pyfaaster/**
    - vendored/**
    - example_handlers.py

provider:
  name: aws
  stage: ${opt:stage, env:WEB_DEFAULT_STAGE, self:custom.defaultStage}
  profile: ${opt:aws-profile, env:AWS_PROFILE, env:AWS_DEFAULT_PROFILE, self:custom.defaultProfile}
  runtime: python3.6
  timeout: 300

  environment:
    PYTHONPATH: "/var/runtime:/var/task/vendored"
    NAMESPACE: ${self:provider.stage}
    LOG_LEVEL: INFO
    CONFIG: <config-bucket-name>

  iamRoleStatements:
  - Effect: Allow
    Action:
      - "lambda:*"
    Resource: "*"
  - Effect: "Allow"
    Action:
      - "kms:*"
    Resource: "*"
  - Effect: "Allow"
    Action:
      - "s3:*"
    Resource: "*"


custom:
  defaultStage: dev
  defaultProfile: default
  defaultEnvironment: dev
  prefix: ${self:service}-${self:provider.stage}

  s3AppBucket: ${self:custom.prefix}-#{AWS::AccountId}
  s3LogBucket: ${self:custom.prefix}-logs-#{AWS::AccountId}

  environment: ${opt:environment, env:WEB_DEFAULT_ENVIRONMENT, self:custom.defaultEnvironment}

functions:
  ExampleFaasterHelloWorld:
    name: ${self:custom.prefix}-faaster-helloworld
    handler: example_handlers.hello_world
    events:
      - http:
          path: hello
          method: get
